import { Teacher, TeacherStatus, AgeGroup } from '@/types';

export const mockTeachers: Teacher[] = [
  {
    id: '1',
    name: '김은영 선생님',
    profileImage: '',
    bio: '한국대 국어교육과 3학년입니다. 평소 아이들을 정말 좋아해서 교육과를 선택했어요. 급하게 연락 주셔도 최대한 빠르게 달려가겠습니다. 책임감 있게 아이를 안전하게 돌봐드릴게요.',
    university: '한국대학교',
    major: '국어교육과',
    grade: '3학년',
    platformExperience: '맘시* 20회, 자란* 15회',
    location: {
      lat: 37.5665,
      lng: 126.9780,
      address: '서울시 서대문구 남가좌동',
    },
    activityRadius: 1000,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 15000,
    experience: 1,
    specialties: ['등하원 도움', '실내놀이', '안전돌봄'],
    ageGroups: [AgeGroup.TODDLER, AgeGroup.PRESCHOOL],
    availability: [
      { dayOfWeek: 1, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 3, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 5, startTime: '15:00', endTime: '21:00', isRecurring: true },
    ],
    rating: 4.9,
    reviewCount: 42,
    verified: true,
    createdAt: new Date('2024-09-15'),
    updatedAt: new Date('2025-01-23'),
    lastActiveAt: new Date(),
    phone: '010-1234-5678',
    responseTime: '5분 이내',
    certificatesCount: 2,
    completedCareCount: 35,
  },
  {
    id: '2',
    name: '이수진 선생님',
    profileImage: '/profile-sujin.png',
    bio: '미래대 수학교육과 4학년입니다. 동생들을 돌본 경험이 많아서 아이들과 금방 친해져요. 긴급한 상황에도 빠르게 대응하고, 부모님이 안심하실 수 있도록 책임감 있게 돌보겠습니다.',
    university: '미래대학교',
    major: '수학교육과',
    grade: '4학년',
    platformExperience: '맘시* 30회, 자란* 25회',
    location: {
      lat: 37.5700,
      lng: 126.9850,
      address: '서울시 서대문구 남가좌동',
    },
    activityRadius: 2000,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 18000,
    experience: 1.5,
    specialties: ['숙제도움', '등하원 동행', '실내놀이'],
    ageGroups: [AgeGroup.PRESCHOOL, AgeGroup.ELEMENTARY],
    availability: [
      { dayOfWeek: 1, startTime: '14:00', endTime: '20:00', isRecurring: true },
      { dayOfWeek: 3, startTime: '14:00', endTime: '20:00', isRecurring: true },
      { dayOfWeek: 5, startTime: '14:00', endTime: '20:00', isRecurring: true },
    ],
    rating: 4.8,
    reviewCount: 56,
    verified: true,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2025-01-22'),
    lastActiveAt: new Date(),
    phone: '010-2345-6789',
    responseTime: '10분 이내',
    certificatesCount: 3,
    completedCareCount: 55,
  },
  {
    id: '3',
    name: '박지혜 선생님',
    profileImage: '/profile-jihye.png',
    bio: '한국대 수학교육과 3학년입니다. 아이들을 진심으로 좋아하고 함께 있으면 저도 행복해져요. 갑작스러운 요청에도 최선을 다해 빠르게 도착하고, 부모님께서 마음 편히 일하실 수 있도록 책임감 있게 돌보겠습니다.',
    university: '한국대학교',
    major: '수학교육과',
    grade: '3학년',
    platformExperience: '맘시* 40회, 자란* 28회',
    location: {
      lat: 37.5600,
      lng: 126.9750,
      address: '서울시 서대문구 남가좌동',
    },
    activityRadius: 500,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 15000,
    experience: 1.5,
    specialties: ['안전돌봄', '실내놀이', '긴급돌봄'],
    ageGroups: [AgeGroup.TODDLER, AgeGroup.PRESCHOOL],
    availability: [
      { dayOfWeek: 0, startTime: '10:00', endTime: '18:00', isRecurring: true },
      { dayOfWeek: 2, startTime: '16:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 4, startTime: '16:00', endTime: '21:00', isRecurring: true },
    ],
    rating: 4.9,
    reviewCount: 67,
    verified: true,
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2025-01-21'),
    lastActiveAt: new Date(),
    phone: '010-3456-7890',
    responseTime: '5분 이내',
    certificatesCount: 2,
    completedCareCount: 68,
  },
  {
    id: '4',
    name: '최민정 선생님',
    profileImage: '',
    bio: '미래대 국어교육과 2학년입니다. 비록 경험은 적지만 아이들을 정말 좋아하고 성실합니다. 긴급 상황에도 빠르게 달려가고, 아이가 즐겁고 안전하게 시간을 보낼 수 있도록 최선을 다하겠습니다.',
    university: '미래대학교',
    major: '국어교육과',
    grade: '2학년',
    platformExperience: '맘시* 12회, 자란* 8회',
    location: {
      lat: 37.5750,
      lng: 126.9900,
      address: '서울시 서대문구 남가좌동',
    },
    activityRadius: 1000,
    status: TeacherStatus.UNAVAILABLE,
    hourlyRate: 15000,
    experience: 0.5,
    specialties: ['등하원 도움', '안전돌봄', '실내놀이'],
    ageGroups: [AgeGroup.ELEMENTARY],
    availability: [
      { dayOfWeek: 1, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 2, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 3, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 4, startTime: '15:00', endTime: '21:00', isRecurring: true },
    ],
    rating: 4.8,
    reviewCount: 28,
    verified: true,
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2025-01-20'),
    lastActiveAt: new Date(),
    phone: '010-4567-8901',
    responseTime: '8분 이내',
    certificatesCount: 1,
    completedCareCount: 20,
  },
  {
    id: '5',
    name: '정유진 선생님',
    profileImage: '',
    bio: '한국대 영어교육과 4학년입니다. 아이들의 웃는 얼굴을 보면 힘이 나요! 급한 일이 생기셨을 때 언제든 연락주세요. 책임감을 갖고 아이를 내 동생처럼 안전하게 돌보겠습니다.',
    university: '한국대학교',
    major: '영어교육과',
    grade: '4학년',
    platformExperience: '맘시* 18회, 자란* 22회',
    location: {
      lat: 37.5550,
      lng: 126.9700,
      address: '서울시 서대문구 남가좌동',
    },
    activityRadius: 2000,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 15000,
    experience: 1,
    specialties: ['영어놀이', '등하원 동행', '숙제도움'],
    ageGroups: [AgeGroup.PRESCHOOL, AgeGroup.ELEMENTARY],
    availability: [
      { dayOfWeek: 0, startTime: '10:00', endTime: '18:00', isRecurring: true },
      { dayOfWeek: 6, startTime: '10:00', endTime: '18:00', isRecurring: true },
    ],
    rating: 4.7,
    reviewCount: 38,
    verified: true,
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2025-01-19'),
    lastActiveAt: new Date(),
    phone: '010-5678-9012',
    responseTime: '10분 이내',
    certificatesCount: 2,
    completedCareCount: 40,
  },
];