import { Teacher, TeacherStatus, AgeGroup } from '@/types';

export const mockTeachers: Teacher[] = [
  {
    id: '1',
    name: '김은영 선생님',
    profileImage: '',
    bio: '10년 경력의 아동 전문 돌봄 선생님입니다. 아이들과 함께하는 시간을 소중히 여기며, 안전하고 즐거운 돌봄을 제공합니다.',
    location: {
      lat: 37.5665,
      lng: 126.9780,
      address: '서울시 중구 명동',
    },
    activityRadius: 1000,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 15000,
    experience: 10,
    specialties: ['놀이지도', '학습지도', '영어교육'],
    ageGroups: [AgeGroup.TODDLER, AgeGroup.PRESCHOOL],
    availability: [
      { dayOfWeek: 1, startTime: '09:00', endTime: '18:00', isRecurring: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '18:00', isRecurring: true },
      { dayOfWeek: 3, startTime: '09:00', endTime: '18:00', isRecurring: true },
    ],
    rating: 4.9,
    reviewCount: 128,
    verified: true,
    createdAt: new Date('2020-01-15'),
    updatedAt: new Date('2024-01-10'),
    lastActiveAt: new Date(),
    phone: '010-1234-5678',
    responseTime: '보통 30분 이내',
    certificatesCount: 3,
    completedCareCount: 342,
  },
  {
    id: '2',
    name: '이수진 선생님',
    profileImage: '',
    bio: '유아교육 전공자로 체계적인 교육과 돌봄을 제공합니다. 창의력 개발과 정서 안정에 중점을 둡니다.',
    location: {
      lat: 37.5700,
      lng: 126.9850,
      address: '서울시 종로구 인사동',
    },
    activityRadius: 2000,
    status: TeacherStatus.RESERVABLE,
    hourlyRate: 18000,
    experience: 7,
    specialties: ['창의미술', '음악놀이', '독서지도'],
    ageGroups: [AgeGroup.PRESCHOOL, AgeGroup.ELEMENTARY],
    availability: [
      { dayOfWeek: 1, startTime: '14:00', endTime: '20:00', isRecurring: true },
      { dayOfWeek: 3, startTime: '14:00', endTime: '20:00', isRecurring: true },
      { dayOfWeek: 5, startTime: '14:00', endTime: '20:00', isRecurring: true },
    ],
    rating: 4.8,
    reviewCount: 95,
    verified: true,
    createdAt: new Date('2021-03-20'),
    updatedAt: new Date('2024-01-09'),
    lastActiveAt: new Date(),
    phone: '010-2345-6789',
    responseTime: '보통 1시간 이내',
    certificatesCount: 4,
    completedCareCount: 267,
  },
  {
    id: '3',
    name: '박지혜 선생님',
    profileImage: '',
    bio: '따뜻한 마음으로 아이들을 돌보는 베테랑 선생님입니다. 영유아 발달에 맞춘 맞춤형 돌봄을 제공합니다.',
    location: {
      lat: 37.5600,
      lng: 126.9750,
      address: '서울시 중구 을지로',
    },
    activityRadius: 500,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 13000,
    experience: 15,
    specialties: ['신생아돌봄', '이유식', '수면교육'],
    ageGroups: [AgeGroup.INFANT, AgeGroup.TODDLER],
    availability: [
      { dayOfWeek: 0, startTime: '09:00', endTime: '17:00', isRecurring: true },
      { dayOfWeek: 2, startTime: '09:00', endTime: '17:00', isRecurring: true },
      { dayOfWeek: 4, startTime: '09:00', endTime: '17:00', isRecurring: true },
    ],
    rating: 4.7,
    reviewCount: 203,
    verified: true,
    createdAt: new Date('2019-06-10'),
    updatedAt: new Date('2024-01-08'),
    lastActiveAt: new Date(),
    phone: '010-3456-7890',
    responseTime: '보통 2시간 이내',
    certificatesCount: 5,
    completedCareCount: 523,
  },
  {
    id: '4',
    name: '최민정 선생님',
    profileImage: '',
    bio: '초등학생 방과후 돌봄 전문가입니다. 숙제 지도와 체험활동을 통한 전인적 성장을 돕습니다.',
    location: {
      lat: 37.5750,
      lng: 126.9900,
      address: '서울시 종로구 삼청동',
    },
    activityRadius: 1000,
    status: TeacherStatus.UNAVAILABLE,
    hourlyRate: 20000,
    experience: 5,
    specialties: ['학습지도', '체육활동', '과학실험'],
    ageGroups: [AgeGroup.ELEMENTARY],
    availability: [
      { dayOfWeek: 1, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 2, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 3, startTime: '15:00', endTime: '21:00', isRecurring: true },
      { dayOfWeek: 4, startTime: '15:00', endTime: '21:00', isRecurring: true },
    ],
    rating: 4.9,
    reviewCount: 67,
    verified: false,
    createdAt: new Date('2022-09-01'),
    updatedAt: new Date('2024-01-07'),
    lastActiveAt: new Date(),
    phone: '010-4567-8901',
    responseTime: '보통 30분 이내',
    certificatesCount: 2,
    completedCareCount: 156,
  },
  {
    id: '5',
    name: '정유진 선생님',
    profileImage: '',
    bio: '아이들의 눈높이에서 소통하는 친구같은 선생님입니다. 재미있고 안전한 돌봄을 약속드립니다.',
    location: {
      lat: 37.5550,
      lng: 126.9700,
      address: '서울시 용산구 이태원',
    },
    activityRadius: 2000,
    status: TeacherStatus.AVAILABLE,
    hourlyRate: 16000,
    experience: 8,
    specialties: ['야외활동', '요리수업', '영어회화'],
    ageGroups: [AgeGroup.PRESCHOOL, AgeGroup.ELEMENTARY],
    availability: [
      { dayOfWeek: 0, startTime: '10:00', endTime: '18:00', isRecurring: true },
      { dayOfWeek: 6, startTime: '10:00', endTime: '18:00', isRecurring: true },
    ],
    rating: 4.6,
    reviewCount: 89,
    verified: true,
    createdAt: new Date('2021-02-15'),
    updatedAt: new Date('2024-01-06'),
    lastActiveAt: new Date(),
    phone: '010-5678-9012',
    responseTime: '보통 1시간 이내',
    certificatesCount: 3,
    completedCareCount: 198,
  },
];